### ISSUE TITLE
Cannot find module "mousetrap-global-bind"

### ISSUE THREAD

**Issue by danielnieto** [koding/shortcuts#5]
I'm trying to use shortcuts from an Electron app, and I'm using webpack to bundle npm packages, it throws this error:

```
Cannot find module "mousetrap-global-bind"
```

**Comment by sinan** [comment]
This package is wrtten to work with `browserify`. I am assuming that's the reason you're getting that error.

Afaik `webpack` doesn't automatically process the `browser` field in`package.json` see [this](https://github.com/koding/shortcuts/blob/master/package.json#L31). But there is a solution here: https://github.com/webpack/webpack/issues/151

**Comment by danielnieto** [comment]
Thank you
